packages:
  - packages/*
  - packages/plugins/*
  - packages/extensions/*
  - packages/languages/*
  - examples/basic
  - examples/transcription
  - examples/kitchensink

catalog:
  typescript: ^5.8.3
  vitest: ^3.0.5
  '@types/node': ^20.0.0