packages:
  - packages/*
  - packages/languages/*
  - packages/plugins/*
  - packages/extensions/*
  - examples/demos/*
  - examples/web-apps/*
  - examples/benchmarks/*
  - docs

catalog:
  typescript: ^5.8.3
  vitest: ^3.0.5
  '@types/node': ^20.0.0
  vite: ^5.2.0
