/**
 * Language Code Management for GLOST
 *
 * Supports flexible language identification:
 * - ISO-639-1: Two-letter codes (en, th, ja)
 * - ISO-639-3: Three-letter codes for precision (eng, tha, jpn, cmn)
 * - BCP-47: Full tags with script/region (en-US, zh-Hans-CN)
 */
import type { z } from "zod";
export { ISO639_1_TO_3, ISO639_3_TO_1, LANGUAGE_DATA, type LanguageEntry, toISO639_3, toISO639_1, getLanguageName, getNativeLanguageName, isValidLanguageCode, parseBCP47, buildBCP47, normalizeBCP47, isValidBCP47, toBCP47WithRegion, type BCP47Components, DEFAULT_REGIONS, SPECIAL_CODES, type SpecialCode, getLanguageInfo, } from "./data/locale.js";
export { type ProficiencyLevel, type ProficiencyStandard, type ProficiencyInfo, CEFR_LEVELS, type CEFRLevel, CEFR_TO_NUMERIC, cefrToNumeric, numericToCEFR, ILR_LEVELS, type ILRLevel, ilrToNumeric, numericToILR, ACTFL_LEVELS, type ACTFLLevel, actflToNumeric, numericToACTFL, HSK_LEVELS, type HSKLevel, hskToNumeric, numericToHSK, JLPT_LEVELS, type JLPTLevel, jlptToNumeric, numericToJLPT, TOPIK_LEVELS, type TOPIKLevel, topikToNumeric, numericToTOPIK, type IELTSBand, ieltsToNumeric, numericToIELTS, type TOEFLScore, toeflToNumeric, numericToTOEFL, CAMBRIDGE_LEVELS, type CambridgeLevel, cambridgeToNumeric, numericToCambridge, DELE_LEVELS, type DELELevel, deleToNumeric, numericToDELE, DELF_LEVELS, DALF_LEVELS, type DELFLevel, type DALFLevel, type FrenchDiplomaLevel, delfDalfToNumeric, numericToDELFDALF, GOETHE_LEVELS, type GoetheLevel, goetheToNumeric, numericToGoethe, toNumericLevel, fromNumericLevel, getProficiencyInfo, meetsLevel, levelProgress, levelsBetween, } from "./data/proficiency.js";
/**
 * Any valid language code (flexible - accepts ISO-639-1, ISO-639-3, or BCP-47)
 */
export type LanguageCode = string;
/**
 * Zod schema for language codes (permissive - validates format only)
 */
export declare const languageCodeSchema: z.ZodUnion<[z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">, z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">, ...z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">[]]>;
export type GlostLanguage = z.infer<typeof languageCodeSchema>;
/**
 * Get display name for any language code
 */
export declare function getLanguageDisplayName(code: string): string;
/**
 * Check if code is a special (non-language) code
 */
export declare function isSpecialCode(code: string): boolean;
/** @deprecated Use GlostLanguage instead */
export type LingoLogLanguage = GlostLanguage;
/** @deprecated Use languageCodeSchema instead */
export declare const glostLanguageSchema: z.ZodUnion<[z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">, z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">, ...z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">[]]>;
export declare const lingoLogLanguageSchema: z.ZodUnion<[z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">, z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">, ...z.ZodLiteral<"spa" | "no" | "ka" | "en" | "th" | "ja" | "ko" | "mr" | "kan" | "ipa" | "ara" | "ar" | "ben" | "bn" | "ces" | "cs" | "dan" | "da" | "deu" | "de" | "ell" | "el" | "eng" | "es" | "fin" | "fi" | "fra" | "fr" | "gu" | "heb" | "he" | "hin" | "hi" | "hun" | "hu" | "ind" | "id" | "ita" | "it" | "jpn" | "kat" | "khm" | "km" | "kn" | "kor" | "lao" | "lo" | "mal" | "ml" | "msa" | "ms" | "mya" | "my" | "nld" | "nl" | "nor" | "pol" | "pl" | "por" | "pt" | "ron" | "ro" | "rus" | "ru" | "swe" | "sv" | "tam" | "ta" | "tel" | "te" | "tha" | "tur" | "tr" | "ukr" | "uk" | "vie" | "vi" | "zho" | "zh" | "cmn" | "yue" | "und" | "mul" | "zxx">[]]>;
export { type CEFRLevel as CefrLevel } from "./data/proficiency.js";
/** @deprecated Use CEFR_LEVELS instead */
export { CEFR_LEVELS as LINGOLOG_CEFR_LEVELS } from "./data/proficiency.js";
/** @deprecated Use CEFRLevel instead */
export { type CEFRLevel as LingoLogCefrLevels } from "./data/proficiency.js";
//# sourceMappingURL=languages.d.ts.map